### ISSUE TITLE
Specifying a function name causes an error

### ISSUE THREAD

**Issue by joshwils82** [HyperBrain/serverless-package-plugin#3]
I am seeing the following when running

`sls package create sites -s josh -r us-east-1`

```
/home/jwilson/.nvm/versions/node/v4.3.2/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

TypeError: Cannot read property 'project' of undefined
  at /home/jwilson/Development/berry/pyramid-api/node_modules/serverless-package-plugin/lib/actions/PackageCreate.js:106:28
  at Array.forEach (native)
  at PackageCreate._validateAndPrepare (/home/jwilson/Development/berry/pyramid-api/node_modules/serverless-package-plugin/lib/actions/PackageCreate.js:105:32)
```

When I do not specify a function, it works successfully.

**Comment by HyperBrain** [comment]
I will prepare a fix in the next days.

**Comment by joshwils82** [comment]
Great, Thanks!
